# Hands-on session
We will be using this notebook for the hands-on portion of the session. Notebooks allow us to run snippets of code without needing to download/configure software. This session was jointly developed by [Dr Sarah Faber](https://github.com/fabsarah/) and Dr Jack Solomon based on earlier workshops by the incomparable [Dr Anisha Khosla](https://github.com/anishakhosla/rtc_workshop/blob/master/python_july2020/complete_PythonWorkshop2020.ipynb)

Let's begin!

## Nuts & Bolts
**Note: To run (execute) the code cells, press control/command + Enter**

You can do math in the python cells
Types of Operations:

Addition: '+'

Subtraction: '-'

Multiplication: '*'

Division: '/'

Exponents: '**'

In [1]:
# addition +

4 + 6

10

In [ ]:

# subtraction -
# multiplication *
# division /

((78-6)*3)/8

# Some general programming anatomy

In [ ]:
# This is a comment! Use this when you want to write notes to humans (the computer will ignore these)
This is not! The computer will pay attention to it.

# And now, the data part!
Let's look at some data. The first thing we're going to do is add the 'pandas' package to our environment. Pandas is a common and useful package in python for dealing with tables, matrices, and other common data forms. If you're working locally, you might need to install the package :

In [ ]:
pip install name_of_package_here
#for example: pip install pandas

We already have pandas, so we can go right to importing it! Whenever you start up an environment, you'll need to add the package(s) you want to use.

In [4]:
# import pandas library as pd

import pandas as pd

#Importing data from a csv file
Often, you'd read a file off of a computer. The code below shows how to do this. If the file is not in the current directory, write the full path name. You can also read in specfic sheets of an excel file using xlrd:

In [ ]:
# function for reading files
pd.read_csv(‘filename.csv’)
pd.read_excel(‘filename.xlsx’)

If you want to get your data out of the python environment and back into a .csv or .xlsx file, you can use the following, remembering to sub in the name of the variable before the .to_csv or .to_excel:

In [ ]:
# function for writing files. Let's pretend we're converting a variable called 'awesome_data':
awesome_data.to_csv(‘filename.csv’)# remember your file extensions!
awesome_data.to_excel(‘filename.xlsx’)

# And now, let's look at some data!
This is a dataset from 2018 on Marvel and DC superhero movies. We have the following data:

*   Title
*   Studio (Marvel or DC)
*   Year of release
*   Tomatometer (Rotten Tomatoes critics' ratings)
*   Popcorn meter (Rotten Tomatoes viewer ratings)
*   Enjoyment (Participant ratings on a 1 (low)-10 (high) Likert scale)
*   Fun (Participant ratings on a 1 (low)-7 (high) Likert scale)
*   Silly (Participant ratings on a 1 (low)-7 (high) Likert scale)
*   NChris (how many Hot Chrises are in this movie)

In [5]:
#Read in some data!

#url = 'https://raw.githubusercontent.com/INN-SFU/SummerResearchBootcamp/main/wSession_1/FilmDataStart.csv' #I think it needs to be set to 'public' for us to open it here
url = 'https://raw.githubusercontent.com/fabsarah/Tutorial_Files/main/FilmDataStart.csv'
super_data = pd.read_csv(url)
super_data #note: this will print ALL of our data. If you want to see the first few lines only, you can use super_data.head()

What are we looking at here?

Scroll through the data and see what you observe

##Initial exploration
Having our data loaded in lets us poke at it a bit. First off, a handy summary!

In [ ]:
super_data.describe()

Observations?

In [14]:
super_data['Year'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018])

In [ ]:
#We can also get the number of unique values if we don't want to sit here and count them (think about how/why this could be helpful)

In [18]:
#Now let's look at some other unique entries:
super_data['NChris'].unique()

array([nan, '1', 'two', 'one', '2', '3'], dtype=object)

In [ ]:
#Let's start poking. Let's find the rows where 'Studio' = 'Marvel':
super_data['Studio'] == 'Marvel'

In [20]:
# And if we want to see the rest of the data, we can use a boolean:
super_data[super_data['Studio'] == 'Marvel']

,Movie,Studio,Year,Tomatometer,Popcorn meter,Enjoyment,Fun,Silly,NChris
15,The Avengers,Marvel,2012,91,91,8.428571,6.194805,2.987013,two
17,Iron Man 3,Marvel,2013,79,78,6.261538,4.615385,4.476923,NaN
19,The Wolverine,Marvel,2013,71,69,6.634146,4.829268,3.804878,NaN
20,Thor: The Dark World,Marvel,2013,67,74,6.619048,4.587302,3.968254,NaN
21,The Amazing Spider-Man 2,Marvel,2014,51,64,5.744186,4.116279,4.534884,NaN
22,Captain America: The Winter Soldier,Marvel,2014,90,92,7.781250,5.359375,2.640625,1
23,Guardians of the Galaxy,Marvel,2013,82,94,8.768293,6.707317,3.658537,one
24,X-Men: Days of Future Past,Marvel,2014,90,91,7.238806,5.089552,3.492537,NaN
25,Ant Man,Marvel,2015,83,85,7.677966,5.644068,4.016949,NaN
26,Avengers: Age of Ultron,Marvel,2015,75,82,6.890411,4.643836,3.917808,2
27,Fantastic Four,Marvel,2015,9,18,4.722222,3.405405,5.552632,NaN
29,Captain America: Civil War,Marvel,2016,90,89,7.164179,4.895522,3.402985,1
30,Deadpool,Marvel,2016,85,90,8.905405,6.662162,4.040541,NaN
31,Doctor Strange,Marvel,2016,89,86,7.682540,5.365079,3.375000,NaN
40,Avengers: Infinity War,Marvel,2018,85,92,NaN,NaN,NaN,3

In [24]:
# ...but we're missing data. Let's start re-coding our variables. Step 1: create a new variable
super_data['Studio_Recoded'] = super_data['Studio']
super_data.head()

,Movie,Studio,Year,Tomatometer,Popcorn meter,Enjoyment,Fun,Silly,NChris,Studio_Recoded
0,Iron Man,1,2008,94,91,7.456790,5.587500,2.790123,NaN,1
1,Punisher: War Zone,1,2008,29,42,4.785714,4.071429,4.785714,NaN,1
2,The Dark Knight,2,2008,94,94,7.455696,4.721519,2.417722,NaN,2
3,The Incredible Hulk,1,2008,68,69,5.444444,4.092593,4.537037,NaN,1
4,Watchmen,2,2009,64,71,6.163265,4.170213,3.469388,NaN,2

In [ ]:
super_data['Studio_Recoded'].replace({'1':'Marvel'})
#now add one in for the DC films

I cannot stress this enough.

# **DO NOT. OVER-WRITE. YOUR ORIGINAL DATA.**
Always make sure you have the original data to roll back to

In [ ]:
#Now let's re-do this with the Chrises. First, create a new column in the dataframe, then start recoding the variables

In [ ]:
#Let's look at the header again to make sure we have a new column

## And now, we think about data visualization
Now that our data are clean (or clean enough for now), let's think about how to look at them

In [ ]:
super_data.describe()

In [ ]:
# Pie charts/bar charts go here!

# What do we want to explore now?
Let's play!

In [45]:
#correlations:
r = super_data['Enjoyment'].corr(super_data['Silly'])
print(r)

-0.8115416506349968

In [48]:
# Or we can get an entire matrix:
super_nums = super_data[["Enjoyment", "Fun","Silly","Tomatometer","Popcorn meter"]]
r = super_nums.corr()
print(r)

               Enjoyment       Fun     Silly  Tomatometer  Popcorn meter
Enjoyment       1.000000  0.906521 -0.811542     0.803916       0.764367
Fun             0.906521  1.000000 -0.589150     0.673432       0.616622
Silly          -0.811542 -0.589150  1.000000    -0.818573      -0.732057
Tomatometer     0.803916  0.673432 -0.818573     1.000000       0.939084
Popcorn meter   0.764367  0.616622 -0.732057     0.939084       1.000000

That's great, but we can also select columns of a particular data type. But what kinds of data do we have?

In [52]:
# dtypes will give us a list of the types of data we have:
super_data.dtypes

Movie              object
Studio             object
Year                int64
Tomatometer         int64
Popcorn meter       int64
Enjoyment         float64
Fun               float64
Silly             float64
NChris             object
Studio_Recoded     object
dtype: object

In [54]:
super_nums = super_data.select_dtypes(include=["float64","int64"])
#super_nums = super_data.select_dtypes(exclude=["?"])
super_nums.head()

   Year  Tomatometer  Popcorn meter  Enjoyment       Fun     Silly
0  2008           94             91   7.456790  5.587500  2.790123
1  2008           29             42   4.785714  4.071429  4.785714
2  2008           94             94   7.455696  4.721519  2.417722
3  2008           68             69   5.444444  4.092593  4.537037
4  2009           64             71   6.163265  4.170213  3.469388

In [77]:
# and let's try it again:
r = super_nums.corr()
print(r)

                   Year  Tomatometer  Popcorn meter  Enjoyment       Fun  \
Year           1.000000     0.179763       0.266976   0.335213  0.226339
Tomatometer    0.179763     1.000000       0.939084   0.803916  0.673432
Popcorn meter  0.266976     0.939084       1.000000   0.764367  0.616622
Enjoyment      0.335213     0.803916       0.764367   1.000000  0.906521
Fun            0.226339     0.673432       0.616622   0.906521  1.000000
Silly         -0.022557    -0.818573      -0.732057  -0.811542 -0.589150

                  Silly
Year          -0.022557
Tomatometer   -0.818573
Popcorn meter -0.732057
Enjoyment     -0.811542
Fun           -0.589150
Silly          1.000000

In [ ]:
# Correlation plot goes here

In [ ]:
#Let's plot some means! Bar plot (or something) goes here:

In [83]:
# Let's try a t-test
import scipy
from scipy.stats import ttest_ind

group1 = super_data[super_data['Studio']=='Marvel']
group2 = super_data[super_data['Studio']=='DC']

ttest_ind(group1['Popcorn meter'], group2['Popcorn meter'])

TtestResult(statistic=np.float64(0.7829775278469207), pvalue=np.float64(0.44441162834435355), df=np.float64(17.0))

In [85]:
ttest_ind(group1.dropna()['Enjoyment'], group2.dropna()['Enjoyment'])

/usr/local/lib/python3.12/dist-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

TtestResult(statistic=np.float64(nan), pvalue=np.float64(nan), df=np.float64(nan))